name: Scrape latest data

on:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron:  '6,26,46 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'  # the actions uses the requirements.txt hash to cache the dependencies
    - run: pip install -r requirements.txt
    - name: Fetch latest data
      run: |-
        # curl https://www.fire.ca.gov/umbraco/Api/IncidentApi/GetIncidents | jq . > incidents.json
        for STORE in "it" "uk" "us" "cn" "ie" "fr" "ca"
        do
            PRODUCTS="stores/$STORE"
            mkdir -p ${PRODUCTS}

            for PRODUCT in "ipads" "iphones" "macs"
            do
                echo "Scraping $STORE $PRODUCT"
            rfrb ${STORE} ${PRODUCT} --format json 2> /dev/null > ${PRODUCTS}/${PRODUCT}.json
            done
        done        
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push